### ISSUE TITLE
How Does The Collision Between User(Camera) and Walls Work?

### ISSUE THREAD

**Issue by lilyzhng** [alvarocasadoc/3December#1]
Hi Álvaro,

Could you let me know how does the collision work here?

I also used static-body component, yet it does not work for me.

The code I have done is here: https://github.com/alchemz/aframe-lab/blob/master/basic.html

Thanks a lot,
Lily

**Comment by lilyzhng** [comment]
Never mind, I figured it out.

I should use univsersal-controls, instead of look-controls and wasd-controls, which allow user to go anyway without limits.

**Comment by alvarocasadoc** [comment]
Hi! I'm happy you figured it out. Yes, I used universal-controls. I also used [kinematic body](https://github.com/donmccurdy/aframe-extras/blob/master/src/misc/kinematic-body.js) in some of the demo projectswhere I used physics.  If you want to know anything else just let me now 😄

**Comment by lilyzhng** [comment]
Sure, thanks for the reply.
